### ISSUE TITLE
Translation for the Greek language

### ISSUE THREAD

**Issue by akittas** [django-wiki/django-wiki#1018]
Hello, i would like to contribute in translating the project to Greek, I have requested the Greek language with my account from `django-wiki` on Transifex but never received a reply. How is it possible to contribute to project translation?

**Comment by benjaoming** [comment]
Hi @akittas - I'm very sorry that you didn't receive a response, good that you opened this issue. I ignored the request because you didn't have a profile on Transifex ([this is 404](https://www.transifex.com/user/profile/telis/)) and thus I couldn't send you a message.

I have contacted Transifex about this previously, and they think it's all fine: That it's just because you have an invisible profile, so as an open source maintainer I should just accept people that I cannot see or verify to coordinate languages :confounded: 

I have accepted the request now, please do stay in touch and let us know if you have completed a translation -- such an update can easily qualify as a patch release if requested.

**Comment by akittas** [comment]
@benjaoming thanks, however I still cannot translate because I am not member of the team, could you accept me so that I can begin the translation?

**Comment by benjaoming** [comment]
It's done!

I think this is related to the same Transifex bug, I never accepted a language proposal from someone and then it got created without that same person as the coordinator.
