### ISSUE TITLE
RFE - Add tags plugin

### ISSUE THREAD

**Issue by FumbleBe** [django-wiki/django-wiki#1103]
It will be really useful if we could add Tags to articles.

Was thinking of a plugin like Help or Macros, displayed on the sidebar.

Possibility to add existing tags to an article, or create a new one then add it.

So, after that we can search articles by tags.

**Comment by benjaoming** [comment]
Hi @FumbleBe

Thanks for opening the suggestion. Tags sound great as a plugin that can be switched on and off, depending on need. It hasn't been requested much, but a few times.

Using the background from #264, what do you think about the permission issues? If we start tagging things, then how will navigating-by-tag be designed? And will tagging be revisioned?

Since you have a concrete usecase, you may be in a better position to analyze this.

**Comment by FumbleBe** [comment]
Thank you for your answer @benjaoming 

Sorry for taking so long.

I cannot agree more with the sentence of yours:

_The problem of tags is that they need quite a lot of work and design to be able to take advantage of. I don't find it very necessary since there is more benefit from putting work into a proper search function and structure of article hierarchy._

Thinking about it, the amount of work needed to achieve that correctly is not worth the benefice...

You can close this one, I will eventually reopen it, if after some time using django-wiki I figure out tags are really missing.

Regards
