### ISSUE TITLE
Is there an elegant way to switch off the revision mechanism?

### ISSUE THREAD

**Issue by kylecapricious2** [django-wiki/django-wiki#1164]
say, I want to use django-wiki to manage my work products, and I don't want the revision system keeping all the revisions every time I makes an trivial change in an article. Also, I may want to edit out some of the contents from an article permanently.

**Comment by benjaoming** [comment]
Hmm, that's not really the use-case of a Wiki

Maybe you could write a separate script that deletes revisions periodically?

**Comment by teury** [comment]
@kylecaprichoso2 
The revision module is part of the internal code of the project.

You can modify the Edition views, so that it does not create new revisions.

It would be good if you explained better what you mean by permanent content. 
You can block the item. That way, article editing and review would be disabled.

https://github.com/django-wiki/django-wiki/blob/12b3f65b5971397a6457bf82ef602ffd346c7203/src/wiki/models/article.py#L348-L350

        default=True

If you change this part to True.
New articles will be blocked.
