### ISSUE TITLE
Warning of illegal attachment types are auto collapsed and thus invisible

### ISSUE THREAD

**Issue by shao-wang-me** [django-wiki/django-wiki#1208]
I am reporting a bug in the attachment plugin.

When you try to upload something illegal (SVG, jpg), it used to (just upgrade from 0.5 to 0.9) show a warning in red text and the Upload a new file section and the section is not collapsed.
Now it still has the warning text but the section is automatically collapsed. This is confusing. Also, the text is in black instead of red (I think it's okay).

After trying to upload SVG:
![image](https://user-images.githubusercontent.com/10136589/190052771-a521cfff-b537-4edf-b6b4-ccfe3a12d378.png)
No warning is shown, but when you click Upload a new file, it's just hidden there:
![image](https://user-images.githubusercontent.com/10136589/190052681-f511a0ac-83f8-4594-977e-8dda4ff206fd.png)

Django version: 4.0.7
Python version: 3.10.5
Platform: Windows 10
django-wiki version: 0.9

**Comment by benjaoming** [comment]
Hi @shao-wang-me ! Thanks for reporting this.

It definitely seems like a bug.

It should probably be fixed in this line, it might be because something has changed in Bootstrap or a wrong assumption about the use of `collapse` and `in`:

https://github.com/django-wiki/django-wiki/blob/main/src/wiki/plugins/attachments/templates/wiki/plugins/attachments/index.html#L79

Is this something you'd be able to patch up?

**Comment by benjaoming** [comment]
Great work @oscarmcm - thanks for fixing this swiftly :+1:
