### ISSUE TITLE
images plugin: Make thumbnail size and position configurable

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#123]
Please note that the wiki is intended for responsive layout techniques and images should not be too assumptive about their context.

**Comment by inflrscns** [comment]
Since thumbnail alignment is now configurable I started working on adding the size option as well, over [here](https://github.com/django-wiki/django-wiki/compare/master...inflrscns:thumbnail-sizes). It's working, but no tests written yet. 

One issue I encountered: now that there are two optional fields, alignment and size, we either have to be strict about the order they come in or use a more complicated regex (or some other solution). 

In the version I linked I took the former approach, but I also wrote a regex that will match the fields in either order. The potential down-side to the latter approach (at least my regex) is it will eat any extra text in the image tag and still render the image, rather than fail to render and display as plain text. For example [image:23 align:left foobar size:small] would still render with the new regex.  

Let me know what you think!

**Comment by benjaoming** [comment]
Hi @inflrscns! Thanks for the work you've done over in your repo - and sorry about not getting back on this. I really like your changes and the idea of Thumbnail sizes. It's quite useful in Mediawiki. Especially the idea of configurable sizes. As the wiki system changes, sysadmins may want to change thumbnail sizes.. having them pixel-hardcoded inside the articles isn't nice.

Could you maybe open up a PR with your changes and we can discuss getting them in?

**Comment by benjaoming** [comment]
Fixed in #612 - will be released in 0.2.2 :)
