### ISSUE TITLE
multiple inheritance causes id clash with django 1.7

### ISSUE THREAD

**Issue by denys-duchier** [django-wiki/django-wiki#255]
in preparation for the upcoming django 1.7 release, I have been trying to port my project; however, django now throws a fit if, when using model inheritance, 2 base models have identically named fields.  This happens in the wiki app:

CommandError: System check identified some issues:

ERRORS:
wiki.ArticleSubscription: (models.E005) The field 'id' from parent model 'wiki.articleplugin' clashes with the field 'id' from parent model 'django_notify.subscription'.

As far as I can tell, one of these 2 id fields needs to be renamed.

**Comment by benjellounayoub** [comment]
Still have the same issue on Django 1.8

**Comment by Pawamoy** [comment]
Why have I been notified about this issue ? :open_mouth: 
There is also a problem in Django when you make 2 models inherit from 1 abstract model, and when this abstract model has a many to many field: https://code.djangoproject.com/ticket/24156

**Comment by benjaoming** [comment]
Oh this is still open? Oops.

It's actually fixed...

https://github.com/django-wiki/django-wiki/blob/master/wiki/plugins/notifications/models.py

So finally because of #288 we won't ever really bother about migrating notification settings from 0.0.24 to 0.1.. and actually it's not to be blamed on 0.0.24 but the problem goes further back. So installing 0.0.24 will cause notifications to reset, but there's a new command to re-create default notification settings for all users.

**Comment by benjaoming** [comment]
Also, @benjellounayoub please try 0.0.24.2 but I can't really know for sure if it actually works with Django 1.8.
