### ISSUE TITLE
Can I access request.user in a Plugin?

### ISSUE THREAD

**Issue by megapctr** [django-wiki/django-wiki#373]
I'm writing a plugin/macro/extension (I'm still tinkering with the code, unsure which is which) for specifying paragraphs visible to anonymous users.

For example, this:

    <public>This is public.</public>
    This is secret.

Would render as `This is public.` for anonymous users, and `This is public. This is secret.` for authenticated and active users.

I'm considering writing a custom markdown extension for my Plugin and a decorator on Plugin.article_view which would snatch the request.user object and store it somewhere in Plugin.

I know this is a horrible solution and I'm open to better solutions. The main challenge here is accessing the User object in a clean, non-suspicious way.

**Comment by benjaoming** [comment]
The request object is not a part of rendering currently. It can never be made a mandatory part, anyways.

The idea of user-dependent or permission-based rendering also breaks caching. We currently have just one cached version of article content. Putting session-dependent data in there would complicate caching quite a lot.

Furthermore, there's the possibility of leakage... so there's a bunch of different extensions, and they might not all obey some permission based constraint. An example is the current article_index which you can find in the macro plugin. It has to avoid showing articles in the indexes that the user has no rights to view. The plugin currently gets around this (since it doesn't know which user is viewing) by never displaying content inside levels that do not have global view perms.

So I'm thinking that to keep things simple and avoid having too much if-this-then-that and to maintain a simple cache, we're better off not including request objects in the rendering.

Do you have any suggestions in relation to these concerns?

**Comment by megapctr** [comment]
I would definitely want to avoid any interference with caching, so I give up on rendering. However, I came up with a different idea - a plugin that is visible to signed in users.

I'm having a tough time getting my test plugin to even show up. Is there some sample plugin I could use for learning how plugins work? I copied attachments plugin, replaced every `attachment` with `foobar` and it still doesn't appear. The code is executed though, as `.pyc` files are created.

**Comment by benjaoming** [comment]
Have you added it to INSTALLED_APPS?

**Comment by megapctr** [comment]
Yes. It's registered in the plugin registry as well.

**Comment by benjaoming** [comment]
Alright, maybe the question was a bit silly :) But exactly what are you looking for to show up?

**Comment by megapctr** [comment]
I expected a `Foobars` tab to appear in the right-hand section with `View`, `Edit`, `Changes`, etc. tabs.

**Comment by benjaoming** [comment]
You should try to do some debugging (regular old print debugging) in wiki_plugin to see that things are accessed and that you have renamed them as they're supposed to... can't really help you more, but come to the IRC, #django-wiki, with questions.
