### ISSUE TITLE
Git integration - Feature Request

### ISSUE THREAD

**Issue by bbcreatv** [django-wiki/django-wiki#402]
Django Waliki has Git integration and is a great feature. Would this be difficult to implement?

**Comment by benjaoming** [comment]
Can you explain more about what kind of "git" you are looking for? Branching of article contents? Cloning? Filesystem based storage?

Is it just having contents in a git repo or is it a specific feature from git that you want?

Because right now, everything is in a database with a linear timeline.. this seems IMO better for a Wiki, but I'm sure it's easy and reasonable to disagree :)

**Comment by benjaoming** [comment]
Hi @bbcreatv 

I've checked out Waliki and it looks like they're having some difficulties creating a UI for the whole git data structure.

This is never gonna happen in django-wiki, and I don't see the point in maintaining non-linear edit histories for this kind of collaborative content writing.. doesn't suit the purpose IMO.

But let's see how they fare.
