### ISSUE TITLE
Include notifications outside of wiki

### ISSUE THREAD

**Issue by Boogymanx** [django-wiki/django-wiki#420]
Hey! I love the django-wiki, it's currently paramount to a project I'm working on. In my project, I have a custom wiki/base.html and this one shows the amount of notifications when browsing the wiki. This page extends the default wiki/base_site.html. 
In other templates, the notification amount doesn't get shown, unless I extend my custom wiki/base.html (which messes up the other content). Do you have a clue what it could be?

Many thanks in advance!

**Comment by benjaoming** [comment]
Appreciate the feedback @Boogymanx :)

As this sounds an awful lot like a support question regarding your own customized template content, please redirect it to the mailing list so the issues here on Github don't get clogged with non-issue as stated in the [guidelines for opening up tickets](https://github.com/django-wiki/django-wiki/blob/master/CONTRIBUTING.md).

Before writing, you should:

1. Notice that the notifications are depending on a javascript file being loaded. So check your browser's javascript console for any possible errors.
2. That the contents of your own customized wik/base.html matters.

"unless I extend my custom wiki/base.html " <- doesn't make sense since if you created your own "wiki/base.html", it would automatically be extended from in all other templates in wiki/*.
