### ISSUE TITLE
Error when adding URL paths through the admin

### ISSUE THREAD

**Issue by artainis** [django-wiki/django-wiki#426]
For articles I made through the admin interface, when I try to add a slug in the URL paths, I get the following error:

IntegrityError at /admin/wiki/urlpath/add/
NOT NULL constraint failed: wiki_urlpath.article_id

If I make an article through the UI default interface, it works though. Why is that?

**Comment by benjaoming** [comment]
First you create the article, then you create its URLPath... but the admin interface doesn't contain the `article` field in the form... that could be possible to add, but it would have to be as a raw foreign key field and not a drop down.

This would be a good first PR for you if you're interested since the other issue you opened has been fixed in another PR ;)
