### ISSUE TITLE
Make Valid Extensions in Attachments Plugin Less Strict

### ISSUE THREAD

**Issue by thomastu** [django-wiki/django-wiki#448]
Having to specify all possible filetypes seems a bit tedious.  In a production environment, the code shouldn't have to change every time to accommodate a valid extension name.  

Some alternative behaviours I would propose instead of [line 67-80 of wiki/plugins/attachments/models](https://github.com/django-wiki/django-wiki/blob/master/wiki/plugins/attachments/models.py#L67):
1.  Accept regex in WIKI_ATTACHMENTS_EXTENSIONS (e.g. 'xl(s|t).?' would then handle 'xlsx', 'xls', 'xlsm', 'xltm', 'xlt') 
2.  Simply don't enforce extensions if APPEND_EXTENSION == True, I'm not sure what security enforcing an extension name gives anyway since any type of file can have any type extension.  appending .upload takes care of the issue of having executables be uploaded, doesn't it?
3.  Store WIKI_ATTACHMENTS_EXTENSIONS in the database and give it an admin, instead of in settings so it can be modified from the default django admin.

**Comment by benjaoming** [comment]
@thomastu security matters for the attachments plugin.

Extensions are about the HTTP servers rules about executing. This is based on extensions. For instance if you have an Apache that calls the PHP cgi when files end with .php would mean you could upload arbitrary code the the server with the .php extension. That's why .upload is always enforced, even though the path is also obscurified.

I agree we could allow regular expressions, especially since we always append .upload anyways, so people are actually somewhat free to mess up and allow *.* :)

**Comment by thomastu** [comment]
@benjaoming Thanks for that clarification!  

Do you think that attachment extensions should be regex by default? or should there be a specific "REGEX_ATTACHMENTS_EXTENSIONS" setting?

**Comment by benjaoming** [comment]
@thomastu you're welcome, sorry that the reply was a bit "tl;dr" :)

I wouldn't like a change that breaks current settings.

But let's consider it:

```
FILE_EXTENSIONS = getattr(
    django_settings, 'WIKI_ATTACHMENTS_EXTENSIONS',
    ['pdf', 'doc', 'odt', 'docx', 'txt'])
```

If we change this to understand regular expressions for extensions, it won't actually break anything. You can just put `.+` in your settings and that would mean "any extension".

You'd have to change this part to match with regular expressions:

https://github.com/django-wiki/django-wiki/blob/master/wiki/plugins/attachments/models.py#L74
