### ISSUE TITLE
Improve navigation

### ISSUE THREAD

**Issue by JamesRamm** [django-wiki/django-wiki#451]
When at the root page of a wiki, you can only see children immediately under the root and only if you click on a fairly innocuous dropdown button.

I'd like to see much more visibility on the navigation, something like this:
- The big white expanse at the left of the contents filled with a sidebar navigation, that is more comprehensive (perhaps a tree structure?)
- The ability to easily embed a table of contents onto a page. Some bit of markup, or an 'insert TOC' button which will generate a TOC giving links to the children of the page being edited.

**Comment by benjaoming** [comment]
I agree that navigation could and should be improved so that new users do not miss out.

django-wiki ships with a default layout that's supposed to be:

1. ...easy to customize (okay not saying that it's easy... just that it's supposed to be)
1. ...responsive!

Sidebar navigation is quite a challenge if you wanna stay responsive and not waste lots of horizontal space below the navigation.

If you want more visibility for the current drop down navigation button, that defeats the purpose of the `[TOC]` ?

Some wikis are very focused on cross-referencing and not so much on hierarchical structure. That structure is actually there to support permissions, not so much to categorize contents.

**Comment by cbsteh** [comment]
What I did was this:
```
<!-- article.html -->
...
<h4>List of articles</h4>
<ul>
  <!-- Need to get the first article (root) -->
  {% url 'wiki:get' path=urlpath.root.path as rootpath %}
  <li>
    <a href="{{ rootpath }}">
      {{ urlpath.root.article.current_revision.title }}
    </a>
  </li>

  <!-- Now get all the descendent articles of the root -->
  {% for child in urlpath.root.get_descendants %}
    <!-- Don't list articles marked for deletion -->
    {% if not child.is_deleted %}
      {% with ''|center:child.level as range %}
        {% for _ in range %}<ul>{% endfor %}
        {% url 'wiki:get' path=child.path as childpath %}
        <li>
          <a href="{{ childpath }}">
            {{ child.article.current_revision.title }}
          </a>
        </li>
        {% for _ in range %}</ul>{% endfor %}
      {% endwith %}
    {% endif %}
  {% endfor %}
</ul>
```
Not sure this is the cleanest or most efficient, but it worked for me.

**Comment by benjaoming** [comment]
Thanks for sharing @cbsteh !

Am keeping this issue open, just to flag that some documentation perhaps is needed so anyone wanting to customize the same way, can have guidance.
