### ISSUE TITLE
Bin for restoring deleted articles

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#458]
If an article is deleted, it becomes invisible. There should be a way for users with moderation access to find and restore articles without going to the django admin.

**Comment by inflrscns** [comment]
@benjaoming I've started working on this a bit in my free time. 

So far it looks like I'll be making a new page to list out all the deleted articles for people with moderation access. I was wondering if you had any suggestions for the name of the page? Right now I'm just using "deleted articles bin" as a placeholder. 

I was also thinking that since I'm already making a new page that only moderators can see, this could turn into a "moderation panel" type of page if you had any additional features you'd like to see on there.

**Comment by benjaoming** [comment]
@inflrscns :+1: Great idea, also with the administration panel outcome. Maybe a start would be a URL namespace like `_admin` and an entry in the user drop down exactly like the one you've placed.

Once more admin functions pop up, there could be a whole section for them... as long as they don't turn into Mediawiki quantities (the Special pages) :)

**Comment by benjaoming** [comment]
This was fixed in 0.1, wondering how I missed closing the issue for over a year :)
