### ISSUE TITLE
docs: Which flavor of mark down is supported?

### ISSUE THREAD

**Issue by guettli** [django-wiki/django-wiki#482]
I am missing a note in the docs which flavor of mark-down is supported.

Please update the docs.

**Comment by benjaoming** [comment]
It takes less time to write what you suggest than to fill in an issue and tell other people to do it.

**Comment by guettli** [comment]
Since I don't know which kind of mark-down is supported, I can't create a pull request.

**Comment by benjaoming** [comment]
By default, it should be the official Markdown:

http://daringfireball.net/projects/markdown/syntax

It's through the implementation of python-markdown.

Then on top of that comes whichever plugins and markdown extensions are enabled.

By adding syntax highlighting, you can get closer to GFM, but we don't have stuff like task lists. I would vouch for adding that GFM is intended to be supported. But this is just an intention, I don't know if it is a good idea since no one ever wanted to discuss if this should be a general goal.

Up until now people have been okay about the level of markdown support, however we could discuss making it easy to add for instance https://github.com/google/py-gfm
