### ISSUE TITLE
Start text block beneath image.

### ISSUE THREAD

**Issue by sverrejb** [django-wiki/django-wiki#496]
I am trying to make a list of text and pictures, where each block of text corresponds to a picture. I have not been able to clear the text so that a new section of text (headed by H1) starts beneath the image from the previous section.

**Comment by benjaoming** [comment]
You mean because images float left or right and you have H1 and want it to not float besides this type of element?

I can see the point, but it's difficult to ensure that floating figures show up besides the blocks they are supposed to.

This is because the screen width is not guaranteed.

I like the idea, though, that h1 clears floating.
