### ISSUE TITLE
Instructions for building a Plugin

### ISSUE THREAD

**Issue by aneesha** [django-wiki/django-wiki#515]
Are there any instructions for building a plugin for django-wiki?

**Comment by benjaoming** [comment]
None better than this:

The plugin API has been stable for a while. It hasn't really been challenged, neither.

But as such, have a look at the existing plugins.

 * attachments: A revisioned plugin that reuses content across articles. Hence, the ReusablePlugin model.
 * images: A revisioned plugin that only works for 1:1 relationships. That is, you can put an image on an article, and then you're expected to use that image only for this article. Changing the image, won't create historical changes in other articles.
 * links and macros: Plugins without models or revisions. An extension for Markdown with interface added to the sidebar.
 * notifications: A plugin that adds a new form to the Settings of an article, namely for users to subscribe to notifications.

Those are the best instructions for now. If you feel like writing documentation of the plugin API, please feel most welcome. Otherwise, the codebase has lots of examples.

I recommend starting by looking at wiki_plugin.py in each plugin.
