### ISSUE TITLE
Request: Live Preview

### ISSUE THREAD

**Issue by lamiru** [django-wiki/django-wiki#529]
I like django-wiki, but I wish it would have a live preview feature.

Like these projects.
- http://markdownlivepreview.com/
- http://realms.io/

**Comment by benjaoming** [comment]
That can't happen, because the Markdown language refers to plugin containers that get rendered server side. For a live preview like this one, the server would be doing a lot of work.

The intention of Markdown is to be simple enough that live previews aren't necessary. Just like when you type in comments on Github.
