### ISSUE TITLE
New default editor - SimpleMDE, EpicEditor or MarkdownDeep?

### ISSUE THREAD

**Issue by ostrokach** [django-wiki/django-wiki#537]
It would be nice if you could select different markdown editors to use with django-wiki. I particularly like [EpicEditor](http://epiceditor.com/), which allows for full screen editing with live preview.

Any pointers on how this could be implemented?

**Comment by benjaoming** [comment]
Have a look here:

https://github.com/django-wiki/django-wiki/tree/master/wiki/editors

I would assume there are some bumps where markitup has been taken too much for granted, especially maybe in some of the plugins' sidebar stuff. If you find this, perhaps refactoring it into methods of the Editor class (for instance, returning JS calls) would be a way forward.. or perhaps a universal JS library interface between the django-wiki plugins and the editor implementation.

**Comment by ostrokach** [comment]
Thanks for the reply!
For the moment I started using Atom with the Atomic Chrome plugin, which allow for live preview and saving progress to a temporary file.

**Comment by benjaoming** [comment]
@ostrokach are you interested in working on this?

**Comment by syslo** [comment]
@benjaoming I can have a look at this. I'll try to implement [SimpleMDE](https://simplemde.com/), [EpicEditor](http://epiceditor.com/) and [MarkdownDeep](http://www.toptensoftware.com/markdowndeep/dingus) editors and identify the necessary changes to the `BaseEditor` or plugins.

**Comment by benjaoming** [comment]
@syslo that sounds great! An editor like SimpleMDE implementing the JS calls made by plugins (inserting images and links) could easily be a new default.

Don't be afraid of having to change the BaseEditor class definition to finalize the API. It's not been tested to implement other editors than MarkItUp.

Btw there's another active issue about changing editor #551 - one should be enough for now, so closing the other :)

**Comment by Forethinker** [comment]
I want to reverse engineer [Gitbook](https://www.gitbook.com) so that django-wiki could take advantage of its amazing [plugin system](https://plugins.gitbook.com/). It is NodeJS based, so it is not a simple task. Also there might be a bit of conflict in handling attachments and images, which will require some overhaul of those plugins. 

From my experiment, users do not put up new revision of images. They simply upload one and then delete/forget them if they don't need them. Also id based reference allows images to be used across different articles, but duplicate images are seldom used and if it was reused, users do not track of those ids and upload the same image again.

Gitbook just dumps all images, attachments and other metadata files into a flat file tree. It allow users to reference them directly by name, so I think is a better UX IMHO.

Going with page based article will require some kind of separator syntax, but all pages can be concatenated and saved together. Waliki and Gitbook both support slide views. This is can achieved using fullPageJS on top of current wiki view.

**Comment by benjaoming** [comment]
The work done by @teury in #587 looks solid enough to prove that we should focus on SimpleMDE.

**Comment by olymk2** [comment]
Just thought i would check on this, do we want simplemde as a default i may put in a PR if this is the case the issue has kind of died of @teury outlined some of the needed changes and i already use simplemde on my own site so happy to fork and try and get it working and then create a PR.

don't want to duplicate effort how ever and if you want to make editors pluggable then that is likely a lot more work although i have not looks at the django wiki code base much so feel free to correct me on that last one.

**Comment by benjaoming** [comment]
@olymk2 
You're commenting on a closed issue - I tried to simplify things for people potentially doing a PR by landing the choice on SimpleMDE -- that's mainly why this issue is closed.

Please do put in a PR, I can outline a strategi in #587
