### ISSUE TITLE
Support for multiple wikis

### ISSUE THREAD

**Issue by mjacksonw** [django-wiki/django-wiki#63]
Title says pretty much all of it. It would be amazing to be able to have multiple wikis on one site, with each Article owned by/associated with a higher level Wiki object.

**Comment by robmoggach** [comment]
I know it's been a while since this subject has been approached - I actually do what distinct wikis with a foreignKey relationship for each wiki to a given parent object which might be a client-facing wiki or an internal project wiki or a public information wiki

I understand that these could exist in the same tree with the above workaround but it doesn't fully address the request for my use case.
