### ISSUE TITLE
setup.py install/develop broken

### ISSUE THREAD

**Issue by spookylukey** [django-wiki/django-wiki#633]
With master, you get the following when doing `setup.py develop` from a repo checkout and fresh virtualenv:

    running develop
    running egg_info
    writing requirements to src/wiki.egg-info/requires.txt
    writing src/wiki.egg-info/PKG-INFO
    writing top-level names to src/wiki.egg-info/top_level.txt
    writing dependency_links to src/wiki.egg-info/dependency_links.txt
    reading manifest file 'src/wiki.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'src/wiki/attachments'
    no previously-included directories found matching 'src/wiki/images'
    warning: no previously-included files found matching 'wiki/locale/en/LC_MESSAGES/django.mo'
    writing manifest file 'src/wiki.egg-info/SOURCES.txt'
    running build_ext
    Creating /home/luke/.virtualenvs/django-wiki/lib/python2.7/site-packages/wiki.egg-link (link to src)
    wiki 0.3.dev20170421193342 is already the active version in easy-install.pth
    
    Installed /home/luke/devel/django-wiki/src
    Processing dependencies for wiki==0.3.dev20170421193342
    Searching for django-nyt>=1.0b1
    Reading https://pypi.python.org/simple/django-nyt/
    No local packages or working download links found for django-nyt>=1.0b1
    error: Could not find suitable distribution for Requirement.parse('django-nyt>=1.0b1')

It looks like it's because the new `django-nyt` package name is `django_nyt` for the lastest betas - looking at https://pypi.python.org/simple/django-nyt/:

    django-nyt-0.9.7.2.tar.gz
    django-nyt-0.9.2.tar.gz
    django-nyt-0.9.4.tar.gz
    django-nyt-0.9.7.3.tar.gz
    django-nyt-0.9.3.tar.gz
    django-nyt-0.9.1.tar.gz
    django-nyt-0.9.7.tar.gz
    django-nyt-0.9.5.tar.gz
    django_nyt-0.9.7.2-py2.py3-none-any.whl
    django_nyt-1.0b2-py2.py3-none-any.whl
    django_nyt-0.9.9-py2.py3-none-any.whl
    django_nyt-0.9.6.post1-py2.py3-none-any.whl
    django-nyt-0.9.tar.gz
    django-nyt-0.9.6.post1.tar.gz
    django_nyt-1.0b1-py2.py3-none-any.whl
    django-nyt-0.9.8.tar.gz
    django_nyt-1.0.dev0-py2.py3-none-any.whl
    django-nyt-0.9.9.tar.gz

However, changing it in `setup.py` produces other problems - if you try to run `tox -e py27-django18` multiple times, you get weird errors after the first time.

Workaround is to manually do:

    pip install django-nyt==1.0b1 

Then:

    ./setup.py develop

It also affects `setup.py install`. I don't know how it would affect `pip install django-wiki`

**Comment by benjaoming** [comment]
Strange! Underscore `_` and dash `-` are supposed to be interchangeable on PyPi. I thought that specifying `>=1.0b1` would allow a pre-release, but maybe if you pin the prerelease `==1.0b1` it will start working again?

In case it doesn't work, I'll try to put a `.tar.gz` on PyPi, I've noticed that there are still situations where it doesn't want to use the `.whl`.

There have been significant changes in Pip lately, so it wouldn't surprise me if they broke an API.

**Comment by benjaoming** [comment]
@spookylukey `pip install -e .` works, and this command also invokes `setup.py develop`, but only after installing dependencies.

Is that acceptable?

Regarding:

> if you try to run tox -e py27-django18 multiple times, you get weird errors after the first time.

I think this might be related to git commits that change the version string (see wiki.__init__ and how the version is dynamically generated).

Have you come across a solution to this by any chance? I basically just delete the `.tox` folder, but of course that's a bit annoying since it takes time to rebuild...

**Comment by benjaoming** [comment]
Responding to myself...

> I think this might be related to git commits that change the version string (see wiki.init and how the version is dynamically generated).

I get it now. It wasn't because the version changed. It was because of a consistency check that only fires when `wiki` is ALREADY installed. So when reusing a tox environment, setuptools wouldn't like the Egg-link because it ALSO had a PYTHONPATH setup that already pointed to `src/` and that one contained the same `wiki, but because of symlinks it appears different to the consistency check.
