### ISSUE TITLE
Restore Attachments - not working?

### ISSUE THREAD

**Issue by Arken94** [django-wiki/django-wiki#669]
Hey, thanks for all the great work on this app. It is much needed!

It seems as though the "Restore attachments" function within the attachments plugin is broken. I initially thought that it had something to do with the code on my local machine, but I tested it on the demo site (which I assume is running the latest stable release) and it did not work there as well. 

Deleted attachments appear in the "restore attachments" tab after deletion, however it appears as plain text and does not allow the user to actually restore the attachment. Check below: 

<img width="1109" alt="screen shot - - at" src="https://user-images.githubusercontent.com/6343555/28723838-0b5bea9e-7386-11e7-9a1c-355a710d239a.png">

"About_downloads.pdf" is listed under restore attachments, but I have no way of actually restoring it. 

Any ideas? Many thanks.

**Comment by floemker** [comment]
Looked shortly into this. It seems that broke with
0d84a9cb0093f0669f5a589c0cbb238b19c7a8b1 .
Since than previous_revision is not set anymore for the new
revision when deleting the attachment. But that is needed for
restoring the attachment (line from the index.html template:
`if attachment.current_revision.previous_revision.id`).

This patch fixes this, but most likely breaks something else. So it's most
likely only a first indicator where to look:

    diff --git src/wiki/plugins/attachments/models.py src/wiki/plugins/attachments/models.py
    index 3f0bbdb..5078f0c 100644
    --- src/wiki/plugins/attachments/models.py
    +++ src/wiki/plugins/attachments/models.py
    @@ -197,7 +197,7 @@ def on_revision_delete(instance, *args, **kwargs):
     @disable_signal_for_loaddata
     def on_attachment_revision_pre_save(**kwargs):
         instance = kwargs['instance']
    -    if kwargs.get('created', False):
    +    if True:
             update_previous_revision = (
                 not instance.previous_revision and
                 instance.attachment and

**Comment by Arken94** [comment]
Awesome work. Closing as per your latest pull request
