### ISSUE TITLE
cannot integrate third party extension mdx_semanticdata due to django-wiki markdown restrictions

### ISSUE THREAD

**Issue by mike-johnson-jr** [django-wiki/django-wiki#713]
I'm trying to use this extension: https://github.com/aleray/mdx_semanticdata with markdown but I am unable to get it to work with django-wiki (though it works in the python/django shell just fine). 

Adding this line 

`%%dc:author :: Sherry Turkle | Turkle's%% %%dc:title::Second Self%% was an early book on the social aspects of computation.`

to a wiki article (with mdx_semanticdata and semanticdata as extensions, see settings.py at the bottom) gives me

`<p><span>Turkle's</span> <span>Second Self</span> was an early book on the social aspects of computation."</p>` 

Whereas doing 

`import markdown
text = "%%dc:author :: Sherry Turkle | Turkle's%% %%dc:title::Second Self%% was an early book on the social aspects of computation."
html = markdown.markdown(text, ['semanticdata'])
print(html)`

In the python shell gives me:

`<p><span content="Sherry Turkle" property="dc:author">Turkle's</span> <span content="Second Self" property="dc:title">Second Self</span> was an early book on the social aspects of computation.</p>`

**Notice the spans from the python shell have content and property tags**. I would like to have the content and property tags in django-wiki. Can anyone help?

My settings.py:

`WIKI_MARKDOWN_KWARGS = {
    'extensions': [
        'semanticdata',
        'footnotes',
        'attr_list',
        'headerid',
        'extra',
        'mdx_semanticdata',
    ],
    'safe_mode': False,
}`

**Comment by benjaoming** [comment]
Sorry about the late response. You should set `WIKI_MARKDOWN_HTML_ATTRIBUTES` to your needs. Please see: http://django-wiki.readthedocs.io/en/master/settings.html

On another note: If you are doing something in particular with data that you want users to model, consider writing a plugin that uses real Django models and implements an actual interface for users to interact with.

That's the deeper motivation of this project. To encourage storing data in a proper relational database, rather than digging valuable data into obscure syntax for users to be baffled by, and for developers to implement complicated parsers for.
