### ISSUE TITLE
Fix error in russian translation

### ISSUE THREAD

**Issue by georgekpg** [django-wiki/django-wiki#764]
I have found a error in russian translation 
(to be concrete, error in translation of #: templates/wiki/root_missing.html:17 )
But I have no idea how I can fix it, or how I can suggest a correct variant.
Please, explain me, howto contribute in translating.

**Comment by georgekpg** [comment]
Ok @benjaoming, I went to transifex.com and found there "join team" button. I have pressed it and now I am waiting for reply on my join team request

**Comment by benjaoming** [comment]
Awesome, I've added you now! Just ping me back when you want the changes pulled in!

**Comment by georgekpg** [comment]
Hi @benjaoming, I have found and fixed that error. 

By the way I have found and fixed a lot of other errors such as: misspellings, confused singular and plural number, poor russian language style, the same method of translating of some terms over all translation (root article for example).
I also have translated 3 new untranslated lines.

Some of my translations where marked with warning because site dictionary wants to find certain words in nominative case in my translation, but they where in other case.

And, after all, I dont know will you trust my translations, or some person should review them first :)

**Comment by benjaoming** [comment]
@georgekpg Thanks so much!!

I will risk accepting translations because most contributors do not try to become regular reviewers or coordinators. So the choice of accepting translations is in most cases left to me as a software maintainer (who doesn't speak Russian/Chinese/Finnish etc).

If you would like to, then you are more than welcome as a reviewer/coordinator of Russian!

For now, I have invited @citxx as a reviewer because he has already translated a lot of the Russian, and maybe he will quickly vouch for you as a co-reviewer based on your contributions.

**Comment by georgekpg** [comment]
Yes, I wlll try to help you with Russian translations. 
Just now I am intergating django-wiki in our project, so I hope it will be useful for all of us :)

And how can I use the fixed translation? Should I upgrade package from git master, or it will be better to wait until next release?

**Comment by benjaoming** [comment]
Yes, they will arrive in `master` first. Notice that we are removing support for Django `<1.11` (anything strictly less that 1.11) in the `master` branch for the upcoming 0.4 release -- this is in order to support Django 2.0.

**Comment by citxx** [comment]
Hi @georgekpg, thank you for all the fixes! I've already looked at some of them and think they are really useful.

@benjaoming, thanks for adding me to reviewers. I already reviewed some of the translations and hope to review others in the nearest future.
