### ISSUE TITLE
Notifications re-creation

### ISSUE THREAD

**Issue by atombrella** [django-wiki/django-wiki#765]
I noticed while running the test project that when you click `Clear notifications list` and then go to:
`_plugin/notifications/` and click `Save changes` an exception: `A user must have a default settings object`.

The test coverage for the notifications plugin is low. I spotted some Django 1.5 legacy. I have a local branch that If you're willing to help finishing it, I could push it.

**Comment by benjaoming** [comment]
@atombrella 

> I noticed while running the test project that when you click `Clear notifications list`

Is this even related to clicking there? The error sounds like perhaps the lookup for a default `Settings` object for a user should be more intelligent, or a behavior to create one should be a bit more sensitive/helpful.

You are right, this behavior is perhaps left a bit too much for people to figure out.

You can see the implementation here: https://github.com/benjaoming/django-nyt/blob/master/django_nyt/models.py#L118

There is a management command [wiki_notifications_create_defaults](https://github.com/django-wiki/django-wiki/blob/master/src/wiki/plugins/notifications/management/commands/wiki_notifications_create_defaults.py) to ensure that users are subscribed to articles that they created, this was because of a previous bug, and in case django-nyt is enabled after the wiki has already been used.

**Comment by benjaoming** [comment]
@atombrella most definitely! `django-nyt` really beckons someone to do a lot of work on user interaction, but in this case, it seems like a good idea to ensure that default settings are auto-generated so things don't needlessly break.

**Comment by benjaoming** [comment]
Is fixed now and tests have been added... thanks @atombrella !
