### ISSUE TITLE
Creating root article triggered a crash

### ISSUE THREAD

**Issue by BillEliot** [django-wiki/django-wiki#935]
I had extended User model and deleted all migrations,
Then I execute:
python3 manager.py makemigrations
python3 manager.py migrate
And I should create a root article,
But I got a crash:

OperationalError at /create-root/
no such table: main.wiki_article__old

my Django version: 2.0.1
my sqlite3 version: 3.6

**Comment by benjaoming** [comment]
> I had extended User model and deleted all migrations,

You cannot extend the user model and migrate afterwards. The Django documentation says more about this.

**Comment by BillEliot** [comment]
I found the real reason, it seems to be a bug in sqlite3, I switched to the Mysql database, the crash disappeared.

**Comment by benjaoming** [comment]
> I found the real reason, it seems to be a bug in sqlite3, I switched to the Mysql database, the crash disappeared.

I don't think that's what fixed it. As I said, if you change the User profile model, you cannot do migrations afterwards. You need to restart everything, recreate the tables etc. It's important to read the documentation about how swappable models and User profiles work in relation to migrations.

**Comment by ckoerber** [comment]
I have encountered a similar issue without modifying the user model (plain `django-wiki` app). My app first seems to work but after modifications I unfortunately cannot recall - it might have been updating `django` - the same error appeared. Also a hard reset of my database
```bash
rm db.sqlite3
python manage.py migrate
```
resulted in the same crash after creating a root model:
```
OperationalError at /create-root/
no such table: main.wiki_article__old
```

The issue was gone after switching to a MySQL database engine.

There might be a correlation with [https://code.djangoproject.com/ticket/29182](https://code.djangoproject.com/ticket/29182) (which is will be fixed in `Django==2.1.5`). 

(My versions: `Django==2.1.4, wiki==0.4.2, sqlite3==3.24.0`)

**Comment by benjaoming** [comment]
@ckoerber did this exception occur while running `manage migrate`, too?

**Comment by ckoerber** [comment]
It appeared when trying to create a root article. Also trying to modify or to delete the (empty) article in the admin view caused the same exception.

**Comment by benjaoming** [comment]
Right right, just wanted to see if it matched the issue description 1:1, because originally, the issue sounded more like the sort of constraint issues you get, if you change the User model and add migrations on top.
