### ISSUE TITLE
Heirarchical page categorization

### ISSUE THREAD

**Issue by DonaldTsang** [django-wiki/django-wiki#963]
For example
https://en.wikipedia.org/wiki/Category:Ranking_functions
has a list of pages and subcategories (Link Analysis),
and also a list of "mother categories" (Information retrieval techniques).

**Comment by benjaoming** [comment]
Hi @DonaldTsang - would you be interested in developing a plugin for categorizing Articles and displaying categories?

I would add that we already have a permission-driven URL Path system that's hierarchical and perhaps something to pay attention to, since permissions may be necessary to take into account when dealing with categories.
